export type PromptItem={title:string;category:string;summary:string;prompt:string};
export const promptLibrary:PromptItem[]=[
{title:"Daily Brain Dump → Action Plan",category:"Productivity & Personal Execution",summary:"Turn unfiltered thoughts into a focused, time-blocked day.",prompt:`Paste your unfiltered thoughts, worries, and ideas below:\n\n[paste brain dump here]\n\nNow transform this into a prioritized, time-blocked day:\n1. Extract all actionable items\n2. Group by context (calls, deep work, admin)\n3. Estimate realistic time for each\n4. Block them into your calendar\n5. Identify what can wait until tomorrow\n\nOutput: A 3-4 hour focused action plan with clear start times.`},
{title:"1:1 Preparation",category:"Leadership & People Management",summary:"Prepare a concise notecard for a focused 30-minute one-to-one.",prompt:`Prepare for a 30-min 1:1 with {{role_title}}:\n\nTALKING POINTS (2-3 things to share):\n- Something I shipped or learned\n- One blocker I need help unblocking\n- A recent win or growth moment\n\nFEEDBACK TO GIVE:\n- One specific, kind observation\n- What they did well this week\n\nASKS & GROWTH:\n- One skill or project I want to develop\n- Support or resources needed\n\nPRIOR ASKS:\nAre any old asks still pending? Follow up.\n\nOutput: 3-5 talking points on a notecard.`},
{title:"Project Status Report",category:"Project & Delivery",summary:"Create a concise stakeholder-ready delivery update.",prompt:`Act as a senior project manager. Using the project information I provide, draft a concise status report covering overall health, accomplishments, milestones, RAID, dependencies, decisions needed, next steps and stakeholder actions. Separate facts from assumptions and do not invent missing dates or metrics.`},
{title:"Root Cause Analysis — Bug Buster",category:"Project & Delivery",summary:"Structure evidence into symptoms, hypotheses, root causes and corrective actions.",prompt:`Act as an experienced delivery and engineering facilitator. Analyse the incident information I provide. Separate observed symptoms from evidence, hypotheses and confirmed root cause. Build a 5-Whys-style analysis where supported, identify contributing conditions, containment, corrective actions, preventive actions, owners and verification measures. Do not claim causation without evidence.`},
{title:"Dashboard Blueprint",category:"Data & Analytics",summary:"Design an actionable KPI dashboard before building it.",prompt:`Design a dashboard blueprint for the business problem I provide. Define audience, decisions supported, KPI definitions, formulas, leading/lagging classification, dimensions, filters, visual recommendations, thresholds, data sources, refresh cadence, data-quality checks and actions triggered by each signal. Avoid vanity metrics.`},
{title:"Define KPIs",category:"Data & Analytics",summary:"Turn an outcome into a measurable KPI system.",prompt:`Given the outcome and context I provide, create a KPI tree with outcome metrics, leading indicators, guardrail metrics and operational measures. For each KPI provide definition, formula, data needed, cadence, owner, interpretation and the action it should trigger. Do not use team metrics to judge individual productivity.`},
{title:"Business Case Builder",category:"Business & Strategy",summary:"Structure a decision-ready business case with assumptions visible.",prompt:`Create a decision-ready business case from the information I provide. Cover problem, strategic rationale, options, benefits, costs, risks, dependencies, assumptions, financial logic, implementation approach, success measures and recommendation. Clearly label missing evidence and assumptions rather than fabricating numbers.`},
{title:"Meeting Notes → Execution",category:"Leadership & Communication",summary:"Convert meeting notes into decisions, actions, risks and dependencies.",prompt:`Transform the meeting notes I provide into: executive summary, decisions made, actions with owner and due date only where explicitly stated, risks, issues, dependencies, open questions and follow-ups. Distinguish confirmed decisions from proposals. Never invent consent or ownership.`},
{title:"PRD → Technical Specification",category:"Product & Technical",summary:"Translate product intent into an implementation-ready technical outline.",prompt:`Translate the PRD I provide into a technical specification covering goals, non-goals, architecture, components, data model, APIs/events, security, observability, error handling, migration considerations, test strategy, rollout/rollback, dependencies, open questions and acceptance criteria. Mark assumptions explicitly.`},
{title:"AI Agent Builder",category:"AI & Agents",summary:"Design a governed agent with tools, permissions and human controls.",prompt:`Design an AI agent for the workflow I provide. Define job-to-be-done, inputs, tools/resources, memory/context, decision boundaries, Read/Recommend/Draft/Execute permissions, human approval points, failure handling, audit trail, evaluation criteria, security/privacy controls and a safe rollout plan.`}
];
export const promptCategories=["All",...Array.from(new Set(promptLibrary.map(p=>p.category)))];
